name: Authentication using Node JS
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use NodeJS version 18
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - run: npm install